USE [INSYS]
GO

---Drop Synonym---
DROP SYNONYM SysUser
DROP SYNONYM SysUserBranch
DROP SYNONYM SysTab

---Create Synonym---
CREATE SYNONYM [ACCEPTANCE] FOR [SEA].[dbo].[ACCEPTANCE]
CREATE SYNONYM [ACCPIC] FOR [SEA].[dbo].[ACCPIC]
CREATE SYNONYM [Cover] FOR [SEA].[dbo].[Cover]
