//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Policy.PSReportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PSReportService.IBuild")]
    public interface IBuild {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/PolicyScheduleAttacmentReport", ReplyAction="http://tempuri.org/IBuild/PolicyScheduleAttacmentReportResponse")]
        E_Policy.PSReportService.PolicyScheduleAttacmentReportResponse PolicyScheduleAttacmentReport(E_Policy.PSReportService.PolicyScheduleAttacmentReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/PolicyScheduleAttacmentReport", ReplyAction="http://tempuri.org/IBuild/PolicyScheduleAttacmentReportResponse")]
        System.Threading.Tasks.Task<E_Policy.PSReportService.PolicyScheduleAttacmentReportResponse> PolicyScheduleAttacmentReportAsync(E_Policy.PSReportService.PolicyScheduleAttacmentReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/PolicyScheduleReport", ReplyAction="http://tempuri.org/IBuild/PolicyScheduleReportResponse")]
        E_Policy.PSReportService.PolicyScheduleReportResponse PolicyScheduleReport(E_Policy.PSReportService.PolicyScheduleReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/PolicyScheduleReport", ReplyAction="http://tempuri.org/IBuild/PolicyScheduleReportResponse")]
        System.Threading.Tasks.Task<E_Policy.PSReportService.PolicyScheduleReportResponse> PolicyScheduleReportAsync(E_Policy.PSReportService.PolicyScheduleReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/PolicyCertificateReport", ReplyAction="http://tempuri.org/IBuild/PolicyCertificateReportResponse")]
        E_Policy.PSReportService.PolicyCertificateReportResponse PolicyCertificateReport(E_Policy.PSReportService.PolicyCertificateReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/PolicyCertificateReport", ReplyAction="http://tempuri.org/IBuild/PolicyCertificateReportResponse")]
        System.Threading.Tasks.Task<E_Policy.PSReportService.PolicyCertificateReportResponse> PolicyCertificateReportAsync(E_Policy.PSReportService.PolicyCertificateReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/PolicyCertificateV2Report", ReplyAction="http://tempuri.org/IBuild/PolicyCertificateV2ReportResponse")]
        string PolicyCertificateV2Report(int Ano, string DestinationFileName, string RPTFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/PolicyCertificateV2Report", ReplyAction="http://tempuri.org/IBuild/PolicyCertificateV2ReportResponse")]
        System.Threading.Tasks.Task<string> PolicyCertificateV2ReportAsync(int Ano, string DestinationFileName, string RPTFileName);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PolicyScheduleAttacmentReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PolicyScheduleAttacmentReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Ano;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OutputFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ErrorMessage;
        
        public PolicyScheduleAttacmentReportRequest() {
        }
        
        public PolicyScheduleAttacmentReportRequest(int Ano, string OutputFileName, string ErrorMessage) {
            this.Ano = Ano;
            this.OutputFileName = OutputFileName;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PolicyScheduleAttacmentReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PolicyScheduleAttacmentReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string PolicyScheduleAttacmentReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public PolicyScheduleAttacmentReportResponse() {
        }
        
        public PolicyScheduleAttacmentReportResponse(string PolicyScheduleAttacmentReportResult, string ErrorMessage) {
            this.PolicyScheduleAttacmentReportResult = PolicyScheduleAttacmentReportResult;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PolicyScheduleReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PolicyScheduleReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Ano;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OutputFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool IsManualSignature;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ErrorMessage;
        
        public PolicyScheduleReportRequest() {
        }
        
        public PolicyScheduleReportRequest(int Ano, string OutputFileName, bool IsManualSignature, string ErrorMessage) {
            this.Ano = Ano;
            this.OutputFileName = OutputFileName;
            this.IsManualSignature = IsManualSignature;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PolicyScheduleReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PolicyScheduleReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string PolicyScheduleReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public PolicyScheduleReportResponse() {
        }
        
        public PolicyScheduleReportResponse(string PolicyScheduleReportResult, string ErrorMessage) {
            this.PolicyScheduleReportResult = PolicyScheduleReportResult;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PolicyCertificateReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PolicyCertificateReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Ano;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OutputFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string RequestUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ErrorMessage;
        
        public PolicyCertificateReportRequest() {
        }
        
        public PolicyCertificateReportRequest(int Ano, string OutputFileName, string RequestUserId, string ErrorMessage) {
            this.Ano = Ano;
            this.OutputFileName = OutputFileName;
            this.RequestUserId = RequestUserId;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PolicyCertificateReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PolicyCertificateReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string PolicyCertificateReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public PolicyCertificateReportResponse() {
        }
        
        public PolicyCertificateReportResponse(string PolicyCertificateReportResult, string ErrorMessage) {
            this.PolicyCertificateReportResult = PolicyCertificateReportResult;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBuildChannel : E_Policy.PSReportService.IBuild, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuildClient : System.ServiceModel.ClientBase<E_Policy.PSReportService.IBuild>, E_Policy.PSReportService.IBuild {
        
        public BuildClient() {
        }
        
        public BuildClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BuildClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuildClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuildClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Policy.PSReportService.PolicyScheduleAttacmentReportResponse E_Policy.PSReportService.IBuild.PolicyScheduleAttacmentReport(E_Policy.PSReportService.PolicyScheduleAttacmentReportRequest request) {
            return base.Channel.PolicyScheduleAttacmentReport(request);
        }
        
        public string PolicyScheduleAttacmentReport(int Ano, string OutputFileName, ref string ErrorMessage) {
            E_Policy.PSReportService.PolicyScheduleAttacmentReportRequest inValue = new E_Policy.PSReportService.PolicyScheduleAttacmentReportRequest();
            inValue.Ano = Ano;
            inValue.OutputFileName = OutputFileName;
            inValue.ErrorMessage = ErrorMessage;
            E_Policy.PSReportService.PolicyScheduleAttacmentReportResponse retVal = ((E_Policy.PSReportService.IBuild)(this)).PolicyScheduleAttacmentReport(inValue);
            ErrorMessage = retVal.ErrorMessage;
            return retVal.PolicyScheduleAttacmentReportResult;
        }
        
        public System.Threading.Tasks.Task<E_Policy.PSReportService.PolicyScheduleAttacmentReportResponse> PolicyScheduleAttacmentReportAsync(E_Policy.PSReportService.PolicyScheduleAttacmentReportRequest request) {
            return base.Channel.PolicyScheduleAttacmentReportAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Policy.PSReportService.PolicyScheduleReportResponse E_Policy.PSReportService.IBuild.PolicyScheduleReport(E_Policy.PSReportService.PolicyScheduleReportRequest request) {
            return base.Channel.PolicyScheduleReport(request);
        }
        
        public string PolicyScheduleReport(int Ano, string OutputFileName, bool IsManualSignature, ref string ErrorMessage) {
            E_Policy.PSReportService.PolicyScheduleReportRequest inValue = new E_Policy.PSReportService.PolicyScheduleReportRequest();
            inValue.Ano = Ano;
            inValue.OutputFileName = OutputFileName;
            inValue.IsManualSignature = IsManualSignature;
            inValue.ErrorMessage = ErrorMessage;
            E_Policy.PSReportService.PolicyScheduleReportResponse retVal = ((E_Policy.PSReportService.IBuild)(this)).PolicyScheduleReport(inValue);
            ErrorMessage = retVal.ErrorMessage;
            return retVal.PolicyScheduleReportResult;
        }
        
        public System.Threading.Tasks.Task<E_Policy.PSReportService.PolicyScheduleReportResponse> PolicyScheduleReportAsync(E_Policy.PSReportService.PolicyScheduleReportRequest request) {
            return base.Channel.PolicyScheduleReportAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Policy.PSReportService.PolicyCertificateReportResponse E_Policy.PSReportService.IBuild.PolicyCertificateReport(E_Policy.PSReportService.PolicyCertificateReportRequest request) {
            return base.Channel.PolicyCertificateReport(request);
        }
        
        public string PolicyCertificateReport(int Ano, string OutputFileName, string RequestUserId, ref string ErrorMessage) {
            E_Policy.PSReportService.PolicyCertificateReportRequest inValue = new E_Policy.PSReportService.PolicyCertificateReportRequest();
            inValue.Ano = Ano;
            inValue.OutputFileName = OutputFileName;
            inValue.RequestUserId = RequestUserId;
            inValue.ErrorMessage = ErrorMessage;
            E_Policy.PSReportService.PolicyCertificateReportResponse retVal = ((E_Policy.PSReportService.IBuild)(this)).PolicyCertificateReport(inValue);
            ErrorMessage = retVal.ErrorMessage;
            return retVal.PolicyCertificateReportResult;
        }
        
        public System.Threading.Tasks.Task<E_Policy.PSReportService.PolicyCertificateReportResponse> PolicyCertificateReportAsync(E_Policy.PSReportService.PolicyCertificateReportRequest request) {
            return base.Channel.PolicyCertificateReportAsync(request);
        }
        
        public string PolicyCertificateV2Report(int Ano, string DestinationFileName, string RPTFileName) {
            return base.Channel.PolicyCertificateV2Report(Ano, DestinationFileName, RPTFileName);
        }
        
        public System.Threading.Tasks.Task<string> PolicyCertificateV2ReportAsync(int Ano, string DestinationFileName, string RPTFileName) {
            return base.Channel.PolicyCertificateV2ReportAsync(Ano, DestinationFileName, RPTFileName);
        }
    }
}
