using System;
using System.IO;

namespace E_Policy.Service.Models
{
    public class CareService
    {
        string defaultCareUserId = "InternalPS";
        PSReportService.BuildClient _PSReportService;
        NonPSReportService.BuildClient _NonPSReportService;
        CareWsCommon.WSCommonSoapClient WsCommonSoapClient;

        public CareService()
        {
            _PSReportService = new PSReportService.BuildClient();
            _NonPSReportService = new NonPSReportService.BuildClient();
            WsCommonSoapClient = new CareWsCommon.WSCommonSoapClient();
        }

        public void GeneratePolicySchedule(int ano, string destinationFile, string rptFile)
        {
            try
            {
                string errorMessage = _PSReportService.PolicyCertificateV2Report(ano, destinationFile, rptFile);
                if (!string.IsNullOrEmpty(errorMessage))
                {
                    throw new Exception(errorMessage);
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public void GeneratePremiumNote(int ano, string destinationFile, string rptFile)
        {
            try
            {
                string errorMessage = _NonPSReportService.PremiumNoteV2Report(ano, destinationFile, rptFile);
                if (!string.IsNullOrEmpty(errorMessage))
                {
                    throw new Exception(errorMessage);
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public void UploadPolicyDocument(int oano, string completeFileName)
        {
            try
            {
                if (!File.Exists(completeFileName)) return;
                
                object[] inputParameter = new object[6];
                object[] outputParameter = new object[1];
                string errorMessage = string.Empty;

                FileInfo fileInfo = new FileInfo(completeFileName);
                inputParameter[0] = oano; //--> OAno
                inputParameter[1] = 0; //--> Keep Zero
                inputParameter[2] = File.ReadAllBytes(completeFileName); //--> File By Array
                inputParameter[3] = fileInfo.Name; //--> File Name
                inputParameter[4] = "This Document Automatically Generated By System"; //--> Description
                inputParameter[5] = fileInfo.Extension.Replace(".", "").ToUpper(); //--> File Type

                WsCommonSoapClient.SavePolicyDocument(defaultCareUserId, string.Empty, inputParameter, ref outputParameter, ref errorMessage);

                if (!string.IsNullOrEmpty(errorMessage))
                {
                    throw new Exception(errorMessage);
                }
            }
            catch (Exception ex)
            {
                throw new Exception(string.Format("{0} | Method : UploadPolicyDocument", ex.Message));
            }
        }
    }
}
