//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Policy.Service.NonPSReportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NonPSReportService.IBuild")]
    public interface IBuild {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/EndorsementAttachmentReport", ReplyAction="http://tempuri.org/IBuild/EndorsementAttachmentReportResponse")]
        E_Policy.Service.NonPSReportService.EndorsementAttachmentReportResponse EndorsementAttachmentReport(E_Policy.Service.NonPSReportService.EndorsementAttachmentReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/EndorsementAttachmentReport", ReplyAction="http://tempuri.org/IBuild/EndorsementAttachmentReportResponse")]
        System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.EndorsementAttachmentReportResponse> EndorsementAttachmentReportAsync(E_Policy.Service.NonPSReportService.EndorsementAttachmentReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/EndorsementReport", ReplyAction="http://tempuri.org/IBuild/EndorsementReportResponse")]
        E_Policy.Service.NonPSReportService.EndorsementReportResponse EndorsementReport(E_Policy.Service.NonPSReportService.EndorsementReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/EndorsementReport", ReplyAction="http://tempuri.org/IBuild/EndorsementReportResponse")]
        System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.EndorsementReportResponse> EndorsementReportAsync(E_Policy.Service.NonPSReportService.EndorsementReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/PremiumNoteReport", ReplyAction="http://tempuri.org/IBuild/PremiumNoteReportResponse")]
        E_Policy.Service.NonPSReportService.PremiumNoteReportResponse PremiumNoteReport(E_Policy.Service.NonPSReportService.PremiumNoteReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/PremiumNoteReport", ReplyAction="http://tempuri.org/IBuild/PremiumNoteReportResponse")]
        System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.PremiumNoteReportResponse> PremiumNoteReportAsync(E_Policy.Service.NonPSReportService.PremiumNoteReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/PremiumNoteV2Report", ReplyAction="http://tempuri.org/IBuild/PremiumNoteV2ReportResponse")]
        string PremiumNoteV2Report(int Ano, string DestinationFile, string RPTFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/PremiumNoteV2Report", ReplyAction="http://tempuri.org/IBuild/PremiumNoteV2ReportResponse")]
        System.Threading.Tasks.Task<string> PremiumNoteV2ReportAsync(int Ano, string DestinationFile, string RPTFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/CoinsuranceFollowerPremiumNoteReport", ReplyAction="http://tempuri.org/IBuild/CoinsuranceFollowerPremiumNoteReportResponse")]
        E_Policy.Service.NonPSReportService.CoinsuranceFollowerPremiumNoteReportResponse CoinsuranceFollowerPremiumNoteReport(E_Policy.Service.NonPSReportService.CoinsuranceFollowerPremiumNoteReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/CoinsuranceFollowerPremiumNoteReport", ReplyAction="http://tempuri.org/IBuild/CoinsuranceFollowerPremiumNoteReportResponse")]
        System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.CoinsuranceFollowerPremiumNoteReportResponse> CoinsuranceFollowerPremiumNoteReportAsync(E_Policy.Service.NonPSReportService.CoinsuranceFollowerPremiumNoteReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/CommissionNoteReport", ReplyAction="http://tempuri.org/IBuild/CommissionNoteReportResponse")]
        E_Policy.Service.NonPSReportService.CommissionNoteReportResponse CommissionNoteReport(E_Policy.Service.NonPSReportService.CommissionNoteReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/CommissionNoteReport", ReplyAction="http://tempuri.org/IBuild/CommissionNoteReportResponse")]
        System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.CommissionNoteReportResponse> CommissionNoteReportAsync(E_Policy.Service.NonPSReportService.CommissionNoteReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/CoinsuranceFollowerCommissionNoteReport", ReplyAction="http://tempuri.org/IBuild/CoinsuranceFollowerCommissionNoteReportResponse")]
        E_Policy.Service.NonPSReportService.CoinsuranceFollowerCommissionNoteReportResponse CoinsuranceFollowerCommissionNoteReport(E_Policy.Service.NonPSReportService.CoinsuranceFollowerCommissionNoteReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/CoinsuranceFollowerCommissionNoteReport", ReplyAction="http://tempuri.org/IBuild/CoinsuranceFollowerCommissionNoteReportResponse")]
        System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.CoinsuranceFollowerCommissionNoteReportResponse> CoinsuranceFollowerCommissionNoteReportAsync(E_Policy.Service.NonPSReportService.CoinsuranceFollowerCommissionNoteReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/FacultativeReport", ReplyAction="http://tempuri.org/IBuild/FacultativeReportResponse")]
        E_Policy.Service.NonPSReportService.FacultativeReportResponse FacultativeReport(E_Policy.Service.NonPSReportService.FacultativeReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/FacultativeReport", ReplyAction="http://tempuri.org/IBuild/FacultativeReportResponse")]
        System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.FacultativeReportResponse> FacultativeReportAsync(E_Policy.Service.NonPSReportService.FacultativeReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/EndorsementFacultativeReport", ReplyAction="http://tempuri.org/IBuild/EndorsementFacultativeReportResponse")]
        E_Policy.Service.NonPSReportService.EndorsementFacultativeReportResponse EndorsementFacultativeReport(E_Policy.Service.NonPSReportService.EndorsementFacultativeReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/EndorsementFacultativeReport", ReplyAction="http://tempuri.org/IBuild/EndorsementFacultativeReportResponse")]
        System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.EndorsementFacultativeReportResponse> EndorsementFacultativeReportAsync(E_Policy.Service.NonPSReportService.EndorsementFacultativeReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/CancellationFacultativeReport", ReplyAction="http://tempuri.org/IBuild/CancellationFacultativeReportResponse")]
        E_Policy.Service.NonPSReportService.CancellationFacultativeReportResponse CancellationFacultativeReport(E_Policy.Service.NonPSReportService.CancellationFacultativeReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuild/CancellationFacultativeReport", ReplyAction="http://tempuri.org/IBuild/CancellationFacultativeReportResponse")]
        System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.CancellationFacultativeReportResponse> CancellationFacultativeReportAsync(E_Policy.Service.NonPSReportService.CancellationFacultativeReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EndorsementAttachmentReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EndorsementAttachmentReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Ano;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OutputFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ErrorMessage;
        
        public EndorsementAttachmentReportRequest() {
        }
        
        public EndorsementAttachmentReportRequest(int Ano, string OutputFileName, string ErrorMessage) {
            this.Ano = Ano;
            this.OutputFileName = OutputFileName;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EndorsementAttachmentReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EndorsementAttachmentReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EndorsementAttachmentReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public EndorsementAttachmentReportResponse() {
        }
        
        public EndorsementAttachmentReportResponse(string EndorsementAttachmentReportResult, string ErrorMessage) {
            this.EndorsementAttachmentReportResult = EndorsementAttachmentReportResult;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EndorsementReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EndorsementReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Ano;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OutputFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string RequestUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ErrorMessage;
        
        public EndorsementReportRequest() {
        }
        
        public EndorsementReportRequest(int Ano, string OutputFileName, string RequestUserId, string ErrorMessage) {
            this.Ano = Ano;
            this.OutputFileName = OutputFileName;
            this.RequestUserId = RequestUserId;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EndorsementReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EndorsementReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EndorsementReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public EndorsementReportResponse() {
        }
        
        public EndorsementReportResponse(string EndorsementReportResult, string ErrorMessage) {
            this.EndorsementReportResult = EndorsementReportResult;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PremiumNoteReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PremiumNoteReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Ano;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OutputFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool IsManualSignature;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ErrorMessage;
        
        public PremiumNoteReportRequest() {
        }
        
        public PremiumNoteReportRequest(int Ano, string OutputFileName, bool IsManualSignature, string ErrorMessage) {
            this.Ano = Ano;
            this.OutputFileName = OutputFileName;
            this.IsManualSignature = IsManualSignature;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PremiumNoteReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PremiumNoteReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string PremiumNoteReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public PremiumNoteReportResponse() {
        }
        
        public PremiumNoteReportResponse(string PremiumNoteReportResult, string ErrorMessage) {
            this.PremiumNoteReportResult = PremiumNoteReportResult;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CoinsuranceFollowerPremiumNoteReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CoinsuranceFollowerPremiumNoteReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Ano;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OutputFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string RequestUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ErrorMessage;
        
        public CoinsuranceFollowerPremiumNoteReportRequest() {
        }
        
        public CoinsuranceFollowerPremiumNoteReportRequest(int Ano, string OutputFileName, string RequestUserId, string ErrorMessage) {
            this.Ano = Ano;
            this.OutputFileName = OutputFileName;
            this.RequestUserId = RequestUserId;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CoinsuranceFollowerPremiumNoteReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CoinsuranceFollowerPremiumNoteReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CoinsuranceFollowerPremiumNoteReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public CoinsuranceFollowerPremiumNoteReportResponse() {
        }
        
        public CoinsuranceFollowerPremiumNoteReportResponse(string CoinsuranceFollowerPremiumNoteReportResult, string ErrorMessage) {
            this.CoinsuranceFollowerPremiumNoteReportResult = CoinsuranceFollowerPremiumNoteReportResult;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CommissionNoteReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CommissionNoteReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Ano;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OutputFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool IsManualSignature;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ErrorMessage;
        
        public CommissionNoteReportRequest() {
        }
        
        public CommissionNoteReportRequest(int Ano, string OutputFileName, bool IsManualSignature, string ErrorMessage) {
            this.Ano = Ano;
            this.OutputFileName = OutputFileName;
            this.IsManualSignature = IsManualSignature;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CommissionNoteReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CommissionNoteReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CommissionNoteReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public CommissionNoteReportResponse() {
        }
        
        public CommissionNoteReportResponse(string CommissionNoteReportResult, string ErrorMessage) {
            this.CommissionNoteReportResult = CommissionNoteReportResult;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CoinsuranceFollowerCommissionNoteReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CoinsuranceFollowerCommissionNoteReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Ano;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OutputFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string RequestUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ErrorMessage;
        
        public CoinsuranceFollowerCommissionNoteReportRequest() {
        }
        
        public CoinsuranceFollowerCommissionNoteReportRequest(int Ano, string OutputFileName, string RequestUserId, string ErrorMessage) {
            this.Ano = Ano;
            this.OutputFileName = OutputFileName;
            this.RequestUserId = RequestUserId;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CoinsuranceFollowerCommissionNoteReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CoinsuranceFollowerCommissionNoteReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CoinsuranceFollowerCommissionNoteReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public CoinsuranceFollowerCommissionNoteReportResponse() {
        }
        
        public CoinsuranceFollowerCommissionNoteReportResponse(string CoinsuranceFollowerCommissionNoteReportResult, string ErrorMessage) {
            this.CoinsuranceFollowerCommissionNoteReportResult = CoinsuranceFollowerCommissionNoteReportResult;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FacultativeReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FacultativeReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Ano;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OutputFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string RequestUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ErrorMessage;
        
        public FacultativeReportRequest() {
        }
        
        public FacultativeReportRequest(int Ano, string OutputFileName, string RequestUserId, string ErrorMessage) {
            this.Ano = Ano;
            this.OutputFileName = OutputFileName;
            this.RequestUserId = RequestUserId;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FacultativeReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FacultativeReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string FacultativeReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public FacultativeReportResponse() {
        }
        
        public FacultativeReportResponse(string FacultativeReportResult, string ErrorMessage) {
            this.FacultativeReportResult = FacultativeReportResult;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EndorsementFacultativeReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EndorsementFacultativeReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Ano;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OutputFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string RequestUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ErrorMessage;
        
        public EndorsementFacultativeReportRequest() {
        }
        
        public EndorsementFacultativeReportRequest(int Ano, string OutputFileName, string RequestUserId, string ErrorMessage) {
            this.Ano = Ano;
            this.OutputFileName = OutputFileName;
            this.RequestUserId = RequestUserId;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EndorsementFacultativeReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EndorsementFacultativeReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EndorsementFacultativeReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public EndorsementFacultativeReportResponse() {
        }
        
        public EndorsementFacultativeReportResponse(string EndorsementFacultativeReportResult, string ErrorMessage) {
            this.EndorsementFacultativeReportResult = EndorsementFacultativeReportResult;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancellationFacultativeReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancellationFacultativeReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Ano;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OutputFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string RequestUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ErrorMessage;
        
        public CancellationFacultativeReportRequest() {
        }
        
        public CancellationFacultativeReportRequest(int Ano, string OutputFileName, string RequestUserId, string ErrorMessage) {
            this.Ano = Ano;
            this.OutputFileName = OutputFileName;
            this.RequestUserId = RequestUserId;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancellationFacultativeReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancellationFacultativeReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CancellationFacultativeReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public CancellationFacultativeReportResponse() {
        }
        
        public CancellationFacultativeReportResponse(string CancellationFacultativeReportResult, string ErrorMessage) {
            this.CancellationFacultativeReportResult = CancellationFacultativeReportResult;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBuildChannel : E_Policy.Service.NonPSReportService.IBuild, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuildClient : System.ServiceModel.ClientBase<E_Policy.Service.NonPSReportService.IBuild>, E_Policy.Service.NonPSReportService.IBuild {
        
        public BuildClient() {
        }
        
        public BuildClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BuildClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuildClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuildClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Policy.Service.NonPSReportService.EndorsementAttachmentReportResponse E_Policy.Service.NonPSReportService.IBuild.EndorsementAttachmentReport(E_Policy.Service.NonPSReportService.EndorsementAttachmentReportRequest request) {
            return base.Channel.EndorsementAttachmentReport(request);
        }
        
        public string EndorsementAttachmentReport(int Ano, string OutputFileName, ref string ErrorMessage) {
            E_Policy.Service.NonPSReportService.EndorsementAttachmentReportRequest inValue = new E_Policy.Service.NonPSReportService.EndorsementAttachmentReportRequest();
            inValue.Ano = Ano;
            inValue.OutputFileName = OutputFileName;
            inValue.ErrorMessage = ErrorMessage;
            E_Policy.Service.NonPSReportService.EndorsementAttachmentReportResponse retVal = ((E_Policy.Service.NonPSReportService.IBuild)(this)).EndorsementAttachmentReport(inValue);
            ErrorMessage = retVal.ErrorMessage;
            return retVal.EndorsementAttachmentReportResult;
        }
        
        public System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.EndorsementAttachmentReportResponse> EndorsementAttachmentReportAsync(E_Policy.Service.NonPSReportService.EndorsementAttachmentReportRequest request) {
            return base.Channel.EndorsementAttachmentReportAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Policy.Service.NonPSReportService.EndorsementReportResponse E_Policy.Service.NonPSReportService.IBuild.EndorsementReport(E_Policy.Service.NonPSReportService.EndorsementReportRequest request) {
            return base.Channel.EndorsementReport(request);
        }
        
        public string EndorsementReport(int Ano, string OutputFileName, string RequestUserId, ref string ErrorMessage) {
            E_Policy.Service.NonPSReportService.EndorsementReportRequest inValue = new E_Policy.Service.NonPSReportService.EndorsementReportRequest();
            inValue.Ano = Ano;
            inValue.OutputFileName = OutputFileName;
            inValue.RequestUserId = RequestUserId;
            inValue.ErrorMessage = ErrorMessage;
            E_Policy.Service.NonPSReportService.EndorsementReportResponse retVal = ((E_Policy.Service.NonPSReportService.IBuild)(this)).EndorsementReport(inValue);
            ErrorMessage = retVal.ErrorMessage;
            return retVal.EndorsementReportResult;
        }
        
        public System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.EndorsementReportResponse> EndorsementReportAsync(E_Policy.Service.NonPSReportService.EndorsementReportRequest request) {
            return base.Channel.EndorsementReportAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Policy.Service.NonPSReportService.PremiumNoteReportResponse E_Policy.Service.NonPSReportService.IBuild.PremiumNoteReport(E_Policy.Service.NonPSReportService.PremiumNoteReportRequest request) {
            return base.Channel.PremiumNoteReport(request);
        }
        
        public string PremiumNoteReport(int Ano, string OutputFileName, bool IsManualSignature, ref string ErrorMessage) {
            E_Policy.Service.NonPSReportService.PremiumNoteReportRequest inValue = new E_Policy.Service.NonPSReportService.PremiumNoteReportRequest();
            inValue.Ano = Ano;
            inValue.OutputFileName = OutputFileName;
            inValue.IsManualSignature = IsManualSignature;
            inValue.ErrorMessage = ErrorMessage;
            E_Policy.Service.NonPSReportService.PremiumNoteReportResponse retVal = ((E_Policy.Service.NonPSReportService.IBuild)(this)).PremiumNoteReport(inValue);
            ErrorMessage = retVal.ErrorMessage;
            return retVal.PremiumNoteReportResult;
        }
        
        public System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.PremiumNoteReportResponse> PremiumNoteReportAsync(E_Policy.Service.NonPSReportService.PremiumNoteReportRequest request) {
            return base.Channel.PremiumNoteReportAsync(request);
        }
        
        public string PremiumNoteV2Report(int Ano, string DestinationFile, string RPTFile) {
            return base.Channel.PremiumNoteV2Report(Ano, DestinationFile, RPTFile);
        }
        
        public System.Threading.Tasks.Task<string> PremiumNoteV2ReportAsync(int Ano, string DestinationFile, string RPTFile) {
            return base.Channel.PremiumNoteV2ReportAsync(Ano, DestinationFile, RPTFile);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Policy.Service.NonPSReportService.CoinsuranceFollowerPremiumNoteReportResponse E_Policy.Service.NonPSReportService.IBuild.CoinsuranceFollowerPremiumNoteReport(E_Policy.Service.NonPSReportService.CoinsuranceFollowerPremiumNoteReportRequest request) {
            return base.Channel.CoinsuranceFollowerPremiumNoteReport(request);
        }
        
        public string CoinsuranceFollowerPremiumNoteReport(int Ano, string OutputFileName, string RequestUserId, ref string ErrorMessage) {
            E_Policy.Service.NonPSReportService.CoinsuranceFollowerPremiumNoteReportRequest inValue = new E_Policy.Service.NonPSReportService.CoinsuranceFollowerPremiumNoteReportRequest();
            inValue.Ano = Ano;
            inValue.OutputFileName = OutputFileName;
            inValue.RequestUserId = RequestUserId;
            inValue.ErrorMessage = ErrorMessage;
            E_Policy.Service.NonPSReportService.CoinsuranceFollowerPremiumNoteReportResponse retVal = ((E_Policy.Service.NonPSReportService.IBuild)(this)).CoinsuranceFollowerPremiumNoteReport(inValue);
            ErrorMessage = retVal.ErrorMessage;
            return retVal.CoinsuranceFollowerPremiumNoteReportResult;
        }
        
        public System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.CoinsuranceFollowerPremiumNoteReportResponse> CoinsuranceFollowerPremiumNoteReportAsync(E_Policy.Service.NonPSReportService.CoinsuranceFollowerPremiumNoteReportRequest request) {
            return base.Channel.CoinsuranceFollowerPremiumNoteReportAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Policy.Service.NonPSReportService.CommissionNoteReportResponse E_Policy.Service.NonPSReportService.IBuild.CommissionNoteReport(E_Policy.Service.NonPSReportService.CommissionNoteReportRequest request) {
            return base.Channel.CommissionNoteReport(request);
        }
        
        public string CommissionNoteReport(int Ano, string OutputFileName, bool IsManualSignature, ref string ErrorMessage) {
            E_Policy.Service.NonPSReportService.CommissionNoteReportRequest inValue = new E_Policy.Service.NonPSReportService.CommissionNoteReportRequest();
            inValue.Ano = Ano;
            inValue.OutputFileName = OutputFileName;
            inValue.IsManualSignature = IsManualSignature;
            inValue.ErrorMessage = ErrorMessage;
            E_Policy.Service.NonPSReportService.CommissionNoteReportResponse retVal = ((E_Policy.Service.NonPSReportService.IBuild)(this)).CommissionNoteReport(inValue);
            ErrorMessage = retVal.ErrorMessage;
            return retVal.CommissionNoteReportResult;
        }
        
        public System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.CommissionNoteReportResponse> CommissionNoteReportAsync(E_Policy.Service.NonPSReportService.CommissionNoteReportRequest request) {
            return base.Channel.CommissionNoteReportAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Policy.Service.NonPSReportService.CoinsuranceFollowerCommissionNoteReportResponse E_Policy.Service.NonPSReportService.IBuild.CoinsuranceFollowerCommissionNoteReport(E_Policy.Service.NonPSReportService.CoinsuranceFollowerCommissionNoteReportRequest request) {
            return base.Channel.CoinsuranceFollowerCommissionNoteReport(request);
        }
        
        public string CoinsuranceFollowerCommissionNoteReport(int Ano, string OutputFileName, string RequestUserId, ref string ErrorMessage) {
            E_Policy.Service.NonPSReportService.CoinsuranceFollowerCommissionNoteReportRequest inValue = new E_Policy.Service.NonPSReportService.CoinsuranceFollowerCommissionNoteReportRequest();
            inValue.Ano = Ano;
            inValue.OutputFileName = OutputFileName;
            inValue.RequestUserId = RequestUserId;
            inValue.ErrorMessage = ErrorMessage;
            E_Policy.Service.NonPSReportService.CoinsuranceFollowerCommissionNoteReportResponse retVal = ((E_Policy.Service.NonPSReportService.IBuild)(this)).CoinsuranceFollowerCommissionNoteReport(inValue);
            ErrorMessage = retVal.ErrorMessage;
            return retVal.CoinsuranceFollowerCommissionNoteReportResult;
        }
        
        public System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.CoinsuranceFollowerCommissionNoteReportResponse> CoinsuranceFollowerCommissionNoteReportAsync(E_Policy.Service.NonPSReportService.CoinsuranceFollowerCommissionNoteReportRequest request) {
            return base.Channel.CoinsuranceFollowerCommissionNoteReportAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Policy.Service.NonPSReportService.FacultativeReportResponse E_Policy.Service.NonPSReportService.IBuild.FacultativeReport(E_Policy.Service.NonPSReportService.FacultativeReportRequest request) {
            return base.Channel.FacultativeReport(request);
        }
        
        public string FacultativeReport(int Ano, string OutputFileName, string RequestUserId, ref string ErrorMessage) {
            E_Policy.Service.NonPSReportService.FacultativeReportRequest inValue = new E_Policy.Service.NonPSReportService.FacultativeReportRequest();
            inValue.Ano = Ano;
            inValue.OutputFileName = OutputFileName;
            inValue.RequestUserId = RequestUserId;
            inValue.ErrorMessage = ErrorMessage;
            E_Policy.Service.NonPSReportService.FacultativeReportResponse retVal = ((E_Policy.Service.NonPSReportService.IBuild)(this)).FacultativeReport(inValue);
            ErrorMessage = retVal.ErrorMessage;
            return retVal.FacultativeReportResult;
        }
        
        public System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.FacultativeReportResponse> FacultativeReportAsync(E_Policy.Service.NonPSReportService.FacultativeReportRequest request) {
            return base.Channel.FacultativeReportAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Policy.Service.NonPSReportService.EndorsementFacultativeReportResponse E_Policy.Service.NonPSReportService.IBuild.EndorsementFacultativeReport(E_Policy.Service.NonPSReportService.EndorsementFacultativeReportRequest request) {
            return base.Channel.EndorsementFacultativeReport(request);
        }
        
        public string EndorsementFacultativeReport(int Ano, string OutputFileName, string RequestUserId, ref string ErrorMessage) {
            E_Policy.Service.NonPSReportService.EndorsementFacultativeReportRequest inValue = new E_Policy.Service.NonPSReportService.EndorsementFacultativeReportRequest();
            inValue.Ano = Ano;
            inValue.OutputFileName = OutputFileName;
            inValue.RequestUserId = RequestUserId;
            inValue.ErrorMessage = ErrorMessage;
            E_Policy.Service.NonPSReportService.EndorsementFacultativeReportResponse retVal = ((E_Policy.Service.NonPSReportService.IBuild)(this)).EndorsementFacultativeReport(inValue);
            ErrorMessage = retVal.ErrorMessage;
            return retVal.EndorsementFacultativeReportResult;
        }
        
        public System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.EndorsementFacultativeReportResponse> EndorsementFacultativeReportAsync(E_Policy.Service.NonPSReportService.EndorsementFacultativeReportRequest request) {
            return base.Channel.EndorsementFacultativeReportAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Policy.Service.NonPSReportService.CancellationFacultativeReportResponse E_Policy.Service.NonPSReportService.IBuild.CancellationFacultativeReport(E_Policy.Service.NonPSReportService.CancellationFacultativeReportRequest request) {
            return base.Channel.CancellationFacultativeReport(request);
        }
        
        public string CancellationFacultativeReport(int Ano, string OutputFileName, string RequestUserId, ref string ErrorMessage) {
            E_Policy.Service.NonPSReportService.CancellationFacultativeReportRequest inValue = new E_Policy.Service.NonPSReportService.CancellationFacultativeReportRequest();
            inValue.Ano = Ano;
            inValue.OutputFileName = OutputFileName;
            inValue.RequestUserId = RequestUserId;
            inValue.ErrorMessage = ErrorMessage;
            E_Policy.Service.NonPSReportService.CancellationFacultativeReportResponse retVal = ((E_Policy.Service.NonPSReportService.IBuild)(this)).CancellationFacultativeReport(inValue);
            ErrorMessage = retVal.ErrorMessage;
            return retVal.CancellationFacultativeReportResult;
        }
        
        public System.Threading.Tasks.Task<E_Policy.Service.NonPSReportService.CancellationFacultativeReportResponse> CancellationFacultativeReportAsync(E_Policy.Service.NonPSReportService.CancellationFacultativeReportRequest request) {
            return base.Channel.CancellationFacultativeReportAsync(request);
        }
    }
}
